### PR TITLE
More additions to PR #43 (WIP: Python bindings)

### PR DESCRIPTION
**Pull request by denis-ismailaj**
Opened a new PR because I couldn't reopen the merged one.

I made some more changes that make `clip.h` `#include`-able directly from C.
This is not necessary for the Python bindings, but since there is overlap I think it is appropriate to introduce these changes together.

To summarize:
- Moved default hparams values out of the struct definitions
- Added the `struct` keyword to function parameter types
- Replaced pass-by-reference params with pointers (only for C-compatible functions, no breaking changes for C++ code)
- Replaced `clip_vocab::id` struct alias with `clip_vocab_id` `typedef` for C code
- Used preprocessor directives to hide the remaining incompatible things that aren't strictly necessary to use the library (e.g. the underlying `std::vector` data fields)

> Used preprocessor directives to hide the remaining incompatible things that aren't strictly necessary to use the library (e.g. the underlying `std::vector` data fields)

Because of this, I had to add "factory" functions for `clip_image_u8` and `clip_image_f32` in order to create them properly from C and then pass pointers back to the C++ methods that populate them.
Side note: I wonder why the `clip.py` code doesn't crash considering that the `data` fields for the image types there are defined as simple arrays and the C++ code assumes them to be `std::vector`s.

There is a working usage example (with hardcoded args) at `examples/main.c`.

### CODE REVIEW

**Comment by monatis** [comment]
Great work, congrats!

`clip.py` works till the end and can print token ids, embeddings and the similarity score, but it gives a segfault at the end of the script. Do you have any idea for why? Maybe double free or something.

**Comment by monatis** [comment]
> I wonder why the clip.py code doesn't crash considering that the data fields for the image types there are defined as simple arrays and the C++ code assumes them to be std::vectors

I couldn't find the exact documentation, but it might be exceptions to strict typing, e.g., type conversions:

> Usually, ctypes does strict type checking. This means, if you have POINTER(c_int) in the argtypes list of a function or as the type of a member field in a structure definition, only instances of exactly the same type are accepted. There are some 
exceptions to this rule, where ctypes accepts other objects. For example, you can pass compatible array instances instead of pointer types. So, for POINTER(c_int), ctypes accepts an array of c_int

Under the "Type conversions" heading [here](https://docs.python.org/3/library/ctypes.html)

**Comment by denis-ismailaj** [comment]
> clip.py works till the end and can print token ids, embeddings and the similarity score, but it gives a segfault at the end of the script. Do you have any idea for why? Maybe double free or something.

Not really sure what the root cause was but it was related to the image structs.
Solved by using the factory functions that are also used in `main.c`.

**Comment by monatis** [comment]
Great, almost there. After fixing the vision config issue it's good to merge. I'll try to have a look tomorrow.

**Pull request merged**
