### PR TITLE
Minor changes for memory management and supporting ffi tools

### PR DESCRIPTION
**Pull request by phronmophobic**
This is a neat project! It was pretty easy to get up in running.

I wrote a small wrapper for it in clojure, https://github.com/phronmophobic/clip.clj.

There were a few small changes to support deleting image data.

Thanks!

### CODE REVIEW

**Comment by monatis** [comment]
Thanks for the contribution! I would prefer the verb `free` instead of `delete` for better consistency with the rest of the code. You can also add a link to your clojure wrapper in the readme. Under `Hot Topics` maybe?

**Comment by phronmophobic** [comment]
> I would prefer the verb free instead of delete for better consistency with the rest of the code. 

That makes sense. I see that `clip_free` uses `free` as a suffix rather than a prefix. I started with `delete_clip_image_u8` and `clean_clip_image_f32` to mirror `make_clip_image_f32`, but don't have any strong feelings. Do you prefer using the verbs as suffixes?

**Comment by monatis** [comment]
Yeah, in fact better to have `clip` as prefix in all namings because it also serves as a namespace. So `clip_image_u8_free` sounds reasonable to me, but you're right, we should also need to update `make` functions accordingly.

**Comment by phronmophobic** [comment]
Cool. I'll update the pull request!

**Comment by phronmophobic** [comment]
Ok, I've updated the pull request. I've tested the newly added functions, but not sure the best way to test the breaking changes like `make_clip_image_u8` -> `clip_image_u8_make`.

**Review by monatis — APPROVED** [review]
Thanks for taking a stab at this! Merging shortly.

**Pull request merged**
