### PR TITLE
Make normalization optional to fix zsl

### LINKED ISSUE #54: Improve zero-shot labeling
As reported in #44, ZSL doesn't match HF's behavior:

After reviewing HF's code for ZSL, I figured out that they don't normalize vectors prior to the dot product calculation in ZSL. In clip.cpp, all encoding functions return normalized vectors, so we need to make normalization optional. This will require a signature change for those functions.

Additionally, we can write a single function that runs the zero-shot labeling task end-to-end, similar to `clip_compare_text_and_image`, and expose that function to the Python binding as well.

### PR DESCRIPTION
**Pull request by monatis**
closes #54 

Since we are already changing function signatures, this might be a good opportunity to use C-compatible signatures everywhere and remove functions with `_c` suffix. WDYT?

### CODE REVIEW

**Comment by denis-ismailaj** [comment]
> Since we are already changing function signatures, this might be a good opportunity to use C-compatible signatures everywhere and remove functions with _c suffix. WDYT?

I think it's better to keep C++ signatures so that it feels natural for users that would like to call the library from C++ code, however we can use preprocessor directives to only expose C-compatible functions when used in C so that we can rename them to have the same names in both cases.

**Comment by monatis** [comment]
> we can use preprocessor directives to only expose C-compatible functions when used in C so that we can rename them to have the same names in both cases

I think functions with the same name with different signatures would make it too confusing. I'd prefer to either keep both versions or expose only C-compatible functions without `_c` suffix, simplifying the API.

**Comment by denis-ismailaj** [comment]
> I think functions with the same name with different signatures would make it too confusing.

Yeah, that's a valid concern.

> expose only C-compatible functions without _c suffix, simplifying the API

In that case, I would recommend making the entire public API in `clip.h` C-compatible to streamline it. This would mean converting some struct fields to simpler types and "hiding" the other structs which don't need to be public in `clip.cpp`.
This seems to be the approach `llama.cpp` has taken as well.

I can open a PR to take a stab at this if that's fine with you.

**Comment by monatis** [comment]
> I would recommend making the entire public API in clip.h C-compatible to streamline it. 

Yeah, this is what I'm also thinking of.

> I can open a PR to take a stab at this if that's fine with you.

That would be awesome. You can target this PR (or directly push to it) and then we can merge to the main branch at once.

Thanks for the colaboration!

**Pull request merged**
