### PR TITLE
Add embedding example

### PR DESCRIPTION
**Pull request by rjadr**
Add an example to retrieve and print text/image embeddings.

### CODE REVIEW

**Comment by monatis** [comment]
Hi @rjadr, thanks for the PR! Does printing all floats in an embedding have a real use case? From what I can see, it adds little value by duplicating some of the existing code. What about making it more interesting and useful? For instance, it can be an example of writing embeddings of multiple images or texts to a Numpy file. writing the function to write floats to .npy file itself should not be so difficult --I can also provide a sample as well.

**Comment by rjadr** [comment]
Hi @monatis, my use case is to have a quick and efficient way to get text/image embeddings. To be honest, I need them in Python so I just collect the stdout in a subprocess, hence printing the outputs. I agree that taking multiple inputs directly would give added value, but what would you suggest to be an efficient way to pass the texts/images in the command line?

**Comment by monatis** [comment]
@rjadr oh got it. I think a more elegant way would be to provide a proper Python binding so that you can make function calls directly from Python. I'll add it soon, hopefully tomorrow. The issue can be tracked in #41.

**Comment by monatis** [comment]
Now that we have Python bindings, I'm closing this PR.

**Pull request closed without merging**
